### ISSUE TITLE
很不错,但是我的闪退

### ISSUE THREAD

**Issue by zhangkun0625** [0x11901/SayHi#1]
非常赞,之前用过类似的但是不知道原理,第一次编译的时候报错NSAlert ,后来我一看导入appKit就好了,
后面编译,注入都是成功了的,但是打开就闪退,跟简述上的那个说的一样,不知道是不是optool电脑环境之类的问题

**Comment by 0x11901** [comment]
这样很难定位。
你可以右键app->显示包内容->Contents->MacOS->打开二进制文件。
看一下console的日志。
或者打开你电脑上的Console.app，找一下日志。

**Comment by zhangkun0625** [comment]
目前是这样的,我用optool注入的就不行,machO文件点上去容易导致finder崩溃,我改用insert_dylib 注入成功后的machO文件跟你的一样16k,但是没效果,我的clang编译出来的dylib我的 8k你那个10k,我用insert_dylib注入然后替换你的那个10k的dylib就OK,我看了clang那个没问题的,而且以前也用这个方法注入也好好的,不会调试,大佬可否加个好友指点下

**Comment by zhangkun0625** [comment]
q61992850

**Comment by zhangkun0625** [comment]
搞定了,我的哥啊,你代码里面放了两个.xm文件有个Tweak_qq.xm,你的脚本里面去找xm文件结果找到两个,然后编译出来的temp.mm文件实际上为空的,后面你吧temp文件删了,又没看到文件,我把Tweak_qq删掉重新跑就好了,但是使用optool估计注入有问题,还是闪退,点击文件导致finder重启不知道原因

**Comment by 0x11901** [comment]
soga，那个是用来搞qq音乐的。我估摸着也没啥人会用，就随便放那里了。
晚上把它删了吧……
